/**
 * @fileoverview Sequential Expansion Agent
 * @module lib/workflow/agents/sequential-expansion
 * @governance EPIC-E4-2
 * @created 2026-01-06
 *
 * Agent that extends conversations by generating follow-up questions
 * and creating child threads for each exploration path.
 *
 * Story E4-2: Sequential Expansion Agent
 *
 * BUG-FIX-2026-01-11: Fixed structured output error with Mistral models
 * - Added modelSupportsStructuredOutput() check
 * - Only send response_format to models that support it (OpenAI, etc.)
 */

import { credentialVault } from '@/lib/agent/providers/credential-vault';
import type { ThreadMessage } from '@/infrastructure/persistence/stores/conversation/types';

// ============================================================================
// Types
// ============================================================================

/**
 * Expansion question generated by the agent
 */
export interface ExpansionQuestion {
    /** Question text */
    question: string;
    /** Brief explanation of why this question is relevant */
    rationale: string;
    /** Suggested title for the child thread */
    threadTitle: string;
}

/**
 * Result of expansion analysis
 */
export interface ExpansionResult {
    /** Follow-up questions generated */
    questions: ExpansionQuestion[];
    /** Summary of the last message's topic */
    topicSummary: string;
    /** Coherence score (0-1) */
    coherenceScore: number;
}

/**
 * Configuration for expansion generation
 */
export interface ExpansionConfig {
    /** Number of questions to generate (default: 3) */
    questionCount?: number;
    /** Provider ID for AI (default: 'gemini') */
    providerId?: string;
    /** Model to use (default: provider's default) */
    modelId?: string;
    /** Temperature for generation (default: 0.7) */
    temperature?: number;
    /** Maximum tokens for response (default: 1024) */
    maxTokens?: number;
}

/**
 * Context from conversation for expansion
 */
export interface ExpansionContext {
    /** Last message from assistant */
    lastMessage: string;
    /** Last user message (optional, for context) */
    lastUserMessage?: string;
    /** Thread title for coherence */
    threadTitle?: string;
    /** Recent conversation history (last N exchanges) */
    recentHistory?: Array<{ role: string; content: string }>;
}

// ============================================================================
// Errors
// ============================================================================

/**
 * Error codes for expansion agent
 */
export const EXPANSION_ERRORS = {
    NO_API_KEY: 'NO_API_KEY',
    API_ERROR: 'API_ERROR',
    INVALID_RESPONSE: 'INVALID_RESPONSE',
    NO_CONTEXT: 'NO_CONTEXT',
} as const;

/**
 * Custom error class for expansion agent
 */
export class ExpansionError extends Error {
    code: keyof typeof EXPANSION_ERRORS;

    constructor(code: keyof typeof EXPANSION_ERRORS, message: string) {
        super(message);
        this.name = 'ExpansionError';
        this.code = code;
    }
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Check if a model supports OpenAI-style structured output (response_format)
 * BUG-FIX-2026-01-11: Prevents API errors with models that don't support response_format
 *
 * Models known to support response_format: { type: 'json_object' }:
 * - OpenAI: gpt-4, gpt-4-turbo, gpt-3.5-turbo, gpt-4o, etc.
 *
 * Models known NOT to support it:
 * - Mistral: mistralai/* (use JSON mode in system prompt instead)
 * - Most free/alternative models via OpenRouter
 */
function modelSupportsStructuredOutput(modelId: string): boolean {
    // OpenAI models support structured output
    if (modelId.startsWith('gpt-')) {
        return true;
    }
    // Claude via OpenAI compatibility (some versions support it)
    if (modelId.includes('claude') && modelId.includes('openai')) {
        return true;
    }
    // Mistral models do NOT support response_format parameter
    if (modelId.includes('mistral')) {
        return false;
    }
    // Default to false for safety - let the model infer JSON from prompt
    return false;
}

// ============================================================================
// Agent Class
// ============================================================================

/**
 * Sequential Expansion Agent
 *
 * Analyzes conversation context and generates follow-up questions
 * that maintain topic coherence and enable deeper exploration.
 */
export class SequentialExpansionAgent {
    private config: Required<ExpansionConfig>;

    constructor(config: ExpansionConfig = {}) {
        this.config = {
            questionCount: config.questionCount ?? 3,
            providerId: config.providerId ?? 'gemini',
            modelId: config.modelId ?? 'gemini-2.0-flash',
            temperature: config.temperature ?? 0.7,
            maxTokens: config.maxTokens ?? 1024,
        };
    }

    /**
     * Generate expansion questions based on conversation context
     *
     * @param context - Conversation context for analysis
     * @returns Expansion result with questions and metadata
     * @throws {ExpansionError} If API call fails or returns invalid response
     */
    async generateExpansions(context: ExpansionContext): Promise<ExpansionResult> {
        // Validate context
        if (!context.lastMessage?.trim()) {
            throw new ExpansionError(
                'NO_CONTEXT',
                'No last message provided for expansion analysis'
            );
        }

        // Get API key
        const apiKey = await credentialVault.getCredentials(this.config.providerId);
        if (!apiKey) {
            throw new ExpansionError(
                'NO_API_KEY',
                `No API key configured for provider "${this.config.providerId}"`
            );
        }

        // Build prompt for expansion
        const prompt = this.buildExpansionPrompt(context);

        // Call API
        const response = await this.callExpansionAPI(prompt, apiKey);

        // Parse response
        const result = this.parseExpansionResponse(response);

        console.log('[SequentialExpansionAgent] Generated', result.questions.length, 'expansions');
        return result;
    }

    /**
     * Build prompt for expansion generation
     */
    private buildExpansionPrompt(context: ExpansionContext): string {
        const parts: string[] = [];

        // System instruction
        parts.push(`You are an expert conversation analyst. Your task is to generate ${this.config.questionCount} thoughtful follow-up questions that deepen the discussion while maintaining topic coherence.`);

        // Context: thread title
        if (context.threadTitle) {
            parts.push(`\nCurrent discussion topic: "${context.threadTitle}"`);
        }

        // Context: recent conversation
        if (context.recentHistory && context.recentHistory.length > 0) {
            parts.push('\nRecent conversation:');
            for (const msg of context.recentHistory.slice(-4)) { // Last 4 messages
                const role = msg.role === 'user' ? 'User' : 'Assistant';
                parts.push(`\n${role}: ${msg.content.slice(0, 200)}${msg.content.length > 200 ? '...' : ''}`);
            }
        }

        // Main instruction
        parts.push(`\nBased on the assistant's last response below, generate ${this.config.questionCount} follow-up questions that:`);
        parts.push('1. Explore different aspects of the topic');
        parts.push('2. Deepen understanding through clarification');
        parts.push('3. Connect to related concepts or practical applications');
        parts.push('\nReturn your response as a JSON array with this structure:');
        parts.push('```json');
        parts.push('[');
        parts.push('  {');
        parts.push('    "question": "Specific question text",');
        parts.push('    "rationale": "Why this question matters for the discussion",');
        parts.push('    "threadTitle": "Concise title for a thread exploring this"');
        parts.push('  }');
        parts.push(']');
        parts.push('```');
        parts.push('\nLast assistant response to analyze:');
        parts.push(context.lastMessage);

        return parts.join('\n');
    }

    /**
     * Call provider API for expansion generation
     */
    private async callExpansionAPI(prompt: string, apiKey: string): Promise<string> {
        const { providerId, modelId, temperature, maxTokens } = this.config;

        let endpoint: string;
        let headers: Record<string, string>;
        let body: object;

        switch (providerId) {
            case 'google':
            case 'gemini':
                endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${modelId}:generateContent?key=${apiKey}`;
                headers = { 'Content-Type': 'application/json' };
                body = {
                    contents: [{ parts: [{ text: prompt }] }],
                    generationConfig: {
                        temperature,
                        maxOutputTokens: maxTokens,
                        responseMimeType: 'application/json',
                    },
                };
                break;

            case 'openrouter':
                endpoint = 'https://openrouter.ai/api/v1/chat/completions';
                headers = {
                    'Authorization': `Bearer ${apiKey}`,
                    'Content-Type': 'application/json',
                    'HTTP-Referer': typeof window !== 'undefined' ? window.location.origin : 'http://localhost',
                    'X-Title': 'Via-gent Sequential Expansion',
                };
                // BUG-FIX-2026-01-11: Only add response_format for models that support it
                const openrouterBody: Record<string, unknown> = {
                    model: modelId,
                    messages: [{ role: 'user', content: prompt }],
                    temperature,
                    max_tokens: maxTokens,
                };
                if (modelSupportsStructuredOutput(modelId)) {
                    openrouterBody.response_format = { type: 'json_object' };
                }
                body = openrouterBody;
                break;

            case 'openai':
                endpoint = 'https://api.openai.com/v1/chat/completions';
                headers = {
                    'Authorization': `Bearer ${apiKey}`,
                    'Content-Type': 'application/json',
                };
                // BUG-FIX-2026-01-11: Only add response_format for models that support it
                const openaiBody: Record<string, unknown> = {
                    model: modelId,
                    messages: [{ role: 'user', content: prompt }],
                    temperature,
                    max_tokens: maxTokens,
                };
                if (modelSupportsStructuredOutput(modelId)) {
                    openaiBody.response_format = { type: 'json_object' };
                }
                body = openaiBody;
                break;

            case 'anthropic':
                endpoint = 'https://api.anthropic.com/v1/messages';
                headers = {
                    'x-api-key': apiKey,
                    'Content-Type': 'application/json',
                    'anthropic-version': '2023-06-01',
                };
                body = {
                    model: modelId,
                    max_tokens: maxTokens,
                    messages: [{ role: 'user', content: prompt }],
                    system: 'You are a conversation analyst. Respond only with valid JSON.',
                };
                break;

            default:
                // OpenAI-compatible fallback
                endpoint = 'https://api.openai.com/v1/chat/completions';
                headers = {
                    'Authorization': `Bearer ${apiKey}`,
                    'Content-Type': 'application/json',
                };
                body = {
                    model: modelId,
                    messages: [{ role: 'user', content: prompt }],
                    temperature,
                    max_tokens: maxTokens,
                };
        }

        const response = await fetch(endpoint, {
            method: 'POST',
            headers,
            body: JSON.stringify(body),
        });

        if (!response.ok) {
            const errorText = await response.text();
            throw new ExpansionError(
                'API_ERROR',
                `API error (${response.status}): ${errorText.slice(0, 200)}`
            );
        }

        const data = await response.json();

        // Extract content based on provider
        if (providerId === 'anthropic') {
            return data.content?.[0]?.text || '';
        } else if (providerId === 'google' || providerId === 'gemini') {
            return data.candidates?.[0]?.content?.parts?.[0]?.text || '';
        } else {
            // OpenAI / OpenRouter format
            return data.choices?.[0]?.message?.content || '';
        }
    }

    /**
     * Parse expansion response from API
     */
    private parseExpansionResponse(response: string): ExpansionResult {
        let parsed: unknown;

        try {
            // Try to parse as JSON
            parsed = JSON.parse(response);
        } catch {
            throw new ExpansionError(
                'INVALID_RESPONSE',
                'API returned non-JSON response'
            );
        }

        // Validate structure
        if (!Array.isArray(parsed)) {
            throw new ExpansionError(
                'INVALID_RESPONSE',
                'Response is not an array of questions'
            );
        }

        const questions: ExpansionQuestion[] = [];

        for (const item of parsed) {
            if (typeof item === 'object' && item !== null) {
                const q = item as Record<string, unknown>;
                if (typeof q.question === 'string' && q.question.trim()) {
                    questions.push({
                        question: q.question.trim(),
                        rationale: typeof q.rationale === 'string' ? q.rationale.trim() : '',
                        threadTitle: typeof q.threadTitle === 'string' && q.threadTitle.trim()
                            ? q.threadTitle.trim()
                            : this.generateThreadTitle(q.question),
                    });
                }
            }
        }

        if (questions.length === 0) {
            throw new ExpansionError(
                'INVALID_RESPONSE',
                'No valid questions found in response'
            );
        }

        // Calculate coherence score based on question variety
        const coherenceScore = this.calculateCoherenceScore(questions);

        // Extract topic summary from first question's rationale
        const topicSummary = questions[0]?.rationale ||
            questions[0]?.question.slice(0, 100) ||
            'Follow-up exploration';

        return {
            questions,
            topicSummary,
            coherenceScore,
        };
    }

    /**
     * Generate a thread title from a question
     */
    private generateThreadTitle(question: string): string {
        // Extract key phrase and truncate
        const words = question.split(/\s+/);
        const maxLength = 50;

        if (question.length <= maxLength) {
            return question;
        }

        let title = '';
        for (const word of words) {
            if (title.length + word.length + 1 > maxLength) {
                break;
            }
            title += (title ? ' ' : '') + word;
        }

        return title + '...';
    }

    /**
     * Calculate coherence score based on question variety
     * Higher score = more diverse questions (good for exploration)
     */
    private calculateCoherenceScore(questions: ExpansionQuestion[]): number {
        if (questions.length < 2) return 1.0;

        // Check for variety in question starts
        const starters = new Set(
            questions.map(q => {
                const firstWord = q.question.split(/\s+/)[0]?.toLowerCase() || '';
                return firstWord;
            })
        );

        const varietyRatio = starters.size / questions.length;

        // Check for variety in question length
        const lengths = questions.map(q => q.question.length);
        const avgLength = lengths.reduce((a, b) => a + b, 0) / lengths.length;
        const lengthVariance = lengths.reduce((sum, len) => sum + Math.abs(len - avgLength), 0) / lengths.length;
        const normalizedVariance = Math.min(lengthVariance / 50, 1); // Cap at 50 char diff

        // Combine metrics (weight variety and length diversity)
        return (varietyRatio * 0.6) + (normalizedVariance * 0.4);
    }
}

// ============================================================================
// Factory Functions
// ============================================================================

/**
 * Create expansion agent with default configuration
 */
export function createExpansionAgent(config?: ExpansionConfig): SequentialExpansionAgent {
    return new SequentialExpansionAgent(config);
}

/**
 * Generate expansions from thread messages
 *
 * Convenience function that extracts context from thread messages
 * and generates expansion questions.
 *
 * @param messages - Thread messages (last message should be from assistant)
 * @param threadTitle - Optional thread title for coherence
 * @param config - Optional expansion configuration
 * @returns Expansion result
 */
export async function generateThreadExpansions(
    messages: ThreadMessage[],
    threadTitle?: string,
    config?: ExpansionConfig
): Promise<ExpansionResult> {
    // Find last assistant message
    const lastAssistantMsg = [...messages].reverse().find(m => m.role === 'assistant');
    const lastUserMsg = [...messages].reverse().find(m => m.role === 'user');

    if (!lastAssistantMsg) {
        throw new ExpansionError(
            'NO_CONTEXT',
            'No assistant message found in thread'
        );
    }

    // Build context
    const context: ExpansionContext = {
        lastMessage: lastAssistantMsg.content,
        lastUserMessage: lastUserMsg?.content,
        threadTitle,
        recentHistory: messages.slice(-6).map(m => ({
            role: m.role,
            content: m.content,
        })),
    };

    // Generate expansions
    const agent = createExpansionAgent(config);
    return agent.generateExpansions(context);
}
