/**
 * @fileoverview Project Zod Schema - Domain Layer
 * @module domain/schemas/project.schema
 *
 * Canonical Zod schema for the Project entity.
 * Types are derived from schemas using z.infer for single source of truth.
 *
 * @epic EPIC-CC-01 - Project Space Foundation
 * @phase 02 - Schema Definitions
 */

import { z } from 'zod';
import { ProjectPluginsSchema } from './plugin.schema';

// ============================================================================
// Nested Schemas
// ============================================================================

/**
 * Layout configuration schema for IDE state restoration.
 */
export const LayoutConfigSchema = z.object({
  panelSizes: z.array(z.number()).optional(),
  openFiles: z.array(z.string()).optional(),
  activeFile: z.string().nullable().optional(),
});

// ============================================================================
// Enum Schemas
// ============================================================================

/**
 * Storage type schema.
 * - 'fsa': File System Access API (local drive)
 * - 'indexeddb': Browser IndexedDB (browser-only)
 */
export const StorageTypeSchema = z.enum(['indexeddb', 'fsa']);

/**
 * Device type schema for platform-specific behavior.
 */
export const DeviceTypeSchema = z.enum(['desktop', 'mobile', 'tablet']);

// ============================================================================
// Project Schema
// ============================================================================

/**
 * Project - Canonical Zod Schema
 *
 * Core project metadata representing a local folder project.
 * This is the single source of truth for Project type definition.
 *
 * Business rules:
 * - Project must have unique id (UUID v4 format)
 * - Storage type must be either 'indexeddb' (browser-only) or 'fsa' (local drive)
 * - Platform determines available plugins based on device type
 * - Soft delete support: deleted projects are recoverable for 30 days
 * - Temp projects are auto-created for standalone Notes access
 *
 * @mandate NO-WORKSPACE - See .planning/architecture/NO-WORKSPACE-MANDATE.md
 */
export const ProjectSchema = z.object({
  // Core identity
  /** UUID v4 or generated ID */
  id: z.string().uuid(),
  /** Display name (typically folder name) */
  name: z.string().min(1).max(255),
  /** Display path for UI (not actual path due to FSA security) */
  folderPath: z.string(),

  // Storage configuration
  /** Storage backend type */
  storageType: StorageTypeSchema,

  // Timestamps
  /** Last time project was opened */
  lastOpened: z.date(),
  /** When project was created */
  createdAt: z.date(),

  // Configuration
  /** Auto-sync flag (default: true) */
  autoSync: z.boolean(),
  /** Optional layout state for IDE restoration */
  layoutState: LayoutConfigSchema.optional(),
  /** Custom exclusion patterns for sync (glob syntax) */
  exclusionPatterns: z.array(z.string()).optional(),

  // Feature flags
  /** File snapshot feature flag */
  fileSnapshotEnabled: z.boolean().optional(),

  // Metadata
  /** Project description (optional) */
  description: z.string().optional(),
  /** Project tags */
  tags: z.array(z.string()),

  // Soft delete support
  /** Soft delete flag (true = marked as deleted, recoverable for 30 days) */
  deleted: z.boolean().optional(),
  /** Timestamp when project was soft deleted */
  deletedAt: z.date().optional(),

  // Temp project support
  /** Temp project flag (auto-created for standalone Notes access) */
  isTemp: z.boolean().optional(),
  /** Auto-created flag (system-generated vs user-created) */
  autoCreated: z.boolean().optional(),
  /** Browser mode flag (special project showing all notes across projects) */
  isBrowserMode: z.boolean().optional(),

  // Platform detection support
  /** Device type for platform-specific behavior */
  deviceType: DeviceTypeSchema.optional(),

  // Plugin configuration (replaces workspaceBindings)
  /** Enabled plugins for this project - platform determines defaults if not specified */
  plugins: ProjectPluginsSchema.optional(),
});

// ============================================================================
// Derived Types
// ============================================================================

/** Project type derived from schema */
export type Project = z.infer<typeof ProjectSchema>;

/** Layout configuration type derived from schema */
export type LayoutConfig = z.infer<typeof LayoutConfigSchema>;

/** Storage type derived from schema */
export type StorageType = z.infer<typeof StorageTypeSchema>;

/** Device type derived from schema */
export type DeviceType = z.infer<typeof DeviceTypeSchema>;

// ============================================================================
// Param Schemas
// ============================================================================

/**
 * Project creation parameters schema.
 * Excludes fields that are auto-generated during creation:
 * - id (generated by system)
 * - createdAt (set to current time)
 * - lastOpened (set to current time)
 */
export const ProjectCreateParamsSchema = ProjectSchema.omit({
  id: true,
  createdAt: true,
  lastOpened: true,
});

/** Project creation parameters type */
export type ProjectCreateParams = z.infer<typeof ProjectCreateParamsSchema>;

/**
 * Project update parameters schema.
 * All fields optional except id (required to identify which project to update).
 */
export const ProjectUpdateParamsSchema = ProjectSchema.partial().required({
  id: true,
});

/** Project update parameters type */
export type ProjectUpdateParams = z.infer<typeof ProjectUpdateParamsSchema>;
