/**
 * Project Entity - Domain Layer
 *
 * Core business entity representing a project in Via-Gent.
 * Aligned with Clean Architecture principles - pure domain logic with no infrastructure dependencies.
 *
 * @layer Domain
 * @module core/entities
 */

/**
 * Workspace binding configuration for project association.
 * Defines which workspaces (IDE, Knowledge, Notes, Study) can access this project.
 */
export interface WorkspaceBindings {
  ide?: boolean;
  notes?: boolean;
  knowledge?: boolean;
  study?: boolean;
}

/**
 * Layout configuration stored per project.
 * Optional - used for restoring IDE state.
 */
export interface LayoutConfig {
  panelSizes?: number[];
  openFiles?: string[];
  activeFile?: string | null;
}

/**
 * Project - Domain Entity
 *
 * Core project metadata representing a local folder project.
 * This is a pure domain entity with NO infrastructure dependencies.
 *
 * Business rules:
 * - Project must have unique id (UUID v4 or generated)
 * - Storage type must be either 'indexeddb' (browser-only) or 'fsa' (local drive with FSA)
 * - Workspace bindings define which workspaces (IDE, Knowledge, Notes, Study) can access this project
 * - Soft delete support: deleted projects are recoverable for 30 days
 * - Temp projects are auto-created for standalone Notes access (NS-2026-01-07)
 *
 * Infrastructure concerns NOT included:
 * - fsaHandle (FileSystemDirectoryHandle) → Browser API, belongs in infrastructure layer
 * - lastKnownPermissionState (FsaPermissionState) → Infrastructure state, belongs in persistence layer
 */
export interface Project {
  // Core identity
  /** UUID v4 or generated ID */
  id: string;
  /** Display name (typically folder name) */
  name: string;
  /** Display path for UI (not actual path due to FSA security) */
  folderPath: string;

  // Storage configuration
  /** Storage backend type: 'fsa' for local drive (requires FSA), 'indexeddb' for browser-only */
  storageType: 'indexeddb' | 'fsa';

  // Timestamps
  /** Last time project was opened */
  lastOpened: Date;
  /** When project was created */
  createdAt: Date;

  // Configuration
  /** Auto-sync flag (default: true) */
  autoSync: boolean;
  /** Optional layout state for IDE restoration */
  layoutState?: LayoutConfig;
  /** Custom exclusion patterns for sync (glob syntax) */
  exclusionPatterns?: string[];

  // Workspace configuration
  /** Workspace binding configuration (IDE, Knowledge, Notes, Study) - ARC-D03: Renamed from bindings */
  workspaceBindings: WorkspaceBindings;

  // Feature flags
  /** File snapshot feature flag */
  fileSnapshotEnabled?: boolean;

  // Metadata
  /** Project description (optional) */
  description?: string;
  /** Project tags (optional) */
  tags: string[];

  // Soft delete support
  /** Soft delete flag (true = marked as deleted, recoverable for 30 days) */
  deleted?: boolean;
  /** Timestamp when project was soft deleted */
  deletedAt?: Date;

  // Temp project support (NS-2026-01-07)
  /** Temp project flag (auto-created for standalone Notes access) */
  isTemp?: boolean;
  /** Auto-created flag (system-generated vs user-created) */
  autoCreated?: boolean;
  /** 45-04: Browser mode flag (special project showing all notes across projects) */
  isBrowserMode?: boolean;

  // Platform detection support (TS-DEBT-01)
  /** Device type for platform-specific behavior (desktop/mobile/tablet) */
  deviceType?: 'desktop' | 'mobile' | 'tablet';
}

/**
 * Project creation parameters (without auto-generated fields)
 *
 * Excludes fields that are auto-generated during creation:
 * - id (generated by system)
 * - createdAt (set to current time)
 * - lastOpened (set to current time)
 */
export type ProjectCreateParams = Omit<
  Project,
  'id' | 'createdAt' | 'lastOpened'
>;

/**
 * Project update parameters (all fields optional except id)
 *
 * Allows partial updates to project metadata.
 * All fields are optional except id (required to identify which project to update).
 */
export type ProjectUpdateParams = Partial<Omit<Project, 'id'>> & { id: string };