/**
 * @fileoverview RAG Chat Service
 * @module lib/rag/rag-chat
 * @governance EPIC-7-5
 *
 * Orchestrates retrieval and generation for RAG chat with citations.
 */

import type { EmbeddingService } from './embedding-service';
import type {
  ChatMessage,
  Citation,
  ExtendedSearchResult,
  RAGChatOptions,
  RAGContext,
} from './types';
import {
  buildContext,
  buildPrompt,
  createCitationsMap,
  formatCitations,
} from './citation-formatter';

/**
 * Hybrid retriever interface (to avoid circular dependency)
 */
interface HybridRetriever {
  search(query: string, options?: any): Promise<ExtendedSearchResult[]>;
}

/**
 * RAG chat service configuration
 */
interface RAGChatConfig {
  /** Hybrid retriever instance */
  retriever: HybridRetriever;

  /** Embedding service */
  embeddingService: EmbeddingService;

  /** Default RAG chat options */
  defaultOptions?: Partial<RAGChatOptions>;
}

/**
 * RAG chat service
 *
 * Orchestrates hybrid retrieval and AI generation for grounded responses.
 */
export class RAGChat {
  private retriever: HybridRetriever;
  private defaultOptions: Partial<RAGChatOptions>;
  private conversationHistory: ChatMessage[] = [];

  constructor(config: RAGChatConfig) {
    this.retriever = config.retriever;
    this.defaultOptions = config.defaultOptions ?? {};
  }

  /**
   * Send a message in RAG chat
   *
   * @param query - User query
   * @param options - RAG chat options
   * @returns Assistant message with citations
   */
  async chat(query: string, options?: RAGChatOptions): Promise<ChatMessage> {
    const opts = { ...this.defaultOptions, ...options };

    // Step 1: Retrieve relevant context
    const context = await this.retrieveContext(query, opts);

    // Step 2: Build prompt with context
    const prompt = buildPrompt(context, query);

    // Step 3: Generate response (simulated - will integrate with TanStack AI)
    const response = await this.generateResponse(prompt, context);

    // Step 4: Format citations
    const citations = formatCitations(context.chunks as any);

    // Step 5: Create message
    const userMessage: ChatMessage = {
      role: 'user',
      content: query,
      timestamp: Date.now(),
    };

    const assistantMessage: ChatMessage = {
      role: 'assistant',
      content: response,
      citations,
      timestamp: Date.now(),
    };

    // Step 6: Update conversation history
    this.addToHistory(userMessage);
    this.addToHistory(assistantMessage);

    return assistantMessage;
  }

  /**
   * Retrieve context for query
   *
   * @param query - User query
   * @param options - RAG chat options
   * @returns RAG context with retrieved chunks
   */
  private async retrieveContext(
    query: string,
    options: RAGChatOptions
  ): Promise<RAGContext> {
    const results = await this.retriever.search(query, {
      limit: options.maxChunks,
      mode: options.searchMode,
    });

    return buildContext(results, query);
  }

  /**
   * Generate response using context (will integrate with TanStack AI)
   *
   * @param prompt - Formatted prompt with context
   * @param context - RAG context
   * @returns Generated response text
   */
  private async generateResponse(_prompt: string, context: RAGContext): Promise<string> {
    // TODO: Integrate with TanStack AI chat endpoint
    // For now, return a placeholder response
    return `Based on the ${context.chunks.length} sources provided, here's an answer to your question. This response will be generated by TanStack AI with streaming support.\n\n[This is a placeholder - will be integrated with /api/chat endpoint]`;
  }

  /**
   * Stream response (will integrate with TanStack AI streaming)
   *
   * @param query - User query
   * @param options - RAG chat options
   * @returns Async generator of response chunks
   */
  async *stream(
    query: string,
    options?: RAGChatOptions
  ): AsyncGenerator<string, ChatMessage, unknown> {
    const opts = { ...this.defaultOptions, ...options };

    // Step 1: Retrieve context
    const context = await this.retrieveContext(query, opts);

    // Step 2: Build prompt (used for TanStack AI integration later)
    buildPrompt(context, query);

    // Step 3: Stream response (TODO: Integrate with TanStack AI)
    // For now, yield placeholder chunks
    const placeholderResponse =
      'Based on the provided sources, here is a streamed response...';

    const words = placeholderResponse.split(' ');
    for (const word of words) {
      yield word + ' ';
    }

    // Step 4: Format citations
    const citations = formatCitations(context.chunks as any);

    // Step 5: Return final message
    const message: ChatMessage = {
      role: 'assistant',
      content: placeholderResponse,
      citations,
      timestamp: Date.now(),
    };

    this.addToHistory(message);
    return message;
  }

  /**
   * Get conversation history
   *
   * @param limit - Maximum messages to return
   * @returns Conversation history
   */
  getHistory(limit?: number): ChatMessage[] {
    if (limit) {
      return this.conversationHistory.slice(-limit);
    }
    return [...this.conversationHistory];
  }

  /**
   * Clear conversation history
   */
  clearHistory(): void {
    this.conversationHistory = [];
  }

  /**
   * Get citations map for quick lookup
   *
   * @param message - Chat message with citations
   * @returns Map of citation ID to citation object
   */
  getCitationsMap(message: ChatMessage): Map<string, Citation> {
    if (!message.citations) {
      return new Map();
    }
    return createCitationsMap(message.citations);
  }

  /**
   * Add message to conversation history
   *
   * @param message - Chat message
   */
  private addToHistory(message: ChatMessage): void {
    this.conversationHistory.push(message);

    // Enforce history limit
    const limit = this.defaultOptions.historyLimit ?? 10;
    if (this.conversationHistory.length > limit * 2) {
      // Keep user/assistant pairs
      this.conversationHistory = this.conversationHistory.slice(-limit * 2);
    }
  }

  /**
   * Build conversation history for prompt
   *
   * @param limit - Maximum messages to include
   * @returns Formatted conversation history
   */
  buildHistoryForPrompt(limit?: number): string {
    const history = this.getHistory(limit);
    return history
      .map((msg) => {
        const role = msg.role === 'user' ? 'User' : 'Assistant';
        return `${role}: ${msg.content}`;
      })
      .join('\n\n');
  }
}

/**
 * Singleton instance (lazy-loaded)
 */
let ragChatInstance: RAGChat | null = null;

export function getRAGChat(config: RAGChatConfig): RAGChat {
  if (!ragChatInstance) {
    ragChatInstance = new RAGChat(config);
  }
  return ragChatInstance;
}
