/**
 * @fileoverview Sequential Expansion Options UI
 * @module presentation/components/chat/SequentialExpansionOptions
 * @governance EPIC-E4-2
 * @created 2026-01-06
 *
 * UI component for displaying follow-up questions and enabling
 * one-click thread expansion.
 *
 * Story E4-2: Sequential Expansion Agent
 */

import { useState } from 'react';
import { ChevronRight, Sparkles, Loader2 } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { useConversationStore } from '@/infrastructure/persistence/stores/conversation/useConversationStore';
import type { ExpansionQuestion, ExpansionResult } from '@/lib/workflow';

// ============================================================================
// Types
// ============================================================================

export interface SequentialExpansionOptionsProps {
    /** Expansion result from agent */
    expansion: ExpansionResult;
    /** Parent thread ID for creating children */
    parentThreadId: string;
    /** Callback when expansion is completed */
    onExpansionComplete?: (childThreadId: string) => void;
    /** Callback when expansion fails */
    onError?: (error: Error) => void;
}

// ============================================================================
// Component
// ============================================================================

/**
 * Sequential Expansion Options
 *
 * Displays follow-up questions generated by the SequentialExpansionAgent
 * and allows one-click creation of child threads.
 */
export function SequentialExpansionOptions({
    expansion,
    parentThreadId,
    onExpansionComplete,
    onError,
}: SequentialExpansionOptionsProps) {
    const { t } = useTranslation();
    const [expandingIndex, setExpandingIndex] = useState<number | null>(null);
    const [expandedThreads, setExpandedThreads] = useState<Set<number>>(new Set());

    // Get thread methods from store
    const getThread = useConversationStore((state) => state.getThread);
    const createThread = useConversationStore((state) => state.createThread);

    /**
     * Handle clicking an expansion question
     * Creates a child thread and initializes it with the question
     */
    const handleExpand = async (index: number, _question: ExpansionQuestion) => {
        if (expandingIndex !== null) return; // Already expanding

        setExpandingIndex(index);

        try {
            // Get parent thread to extract conversationId
            const parentThread = getThread(parentThreadId);
            if (!parentThread) {
                throw new Error('Parent thread not found');
            }

            // Create child thread with the question as title
            const childThreadId = createThread(parentThread.conversationId, parentThreadId);

            // TODO: Initialize the new thread with the question as the first user message
            // This requires the addMessage method from the store
            // For now, just notify completion

            setExpandedThreads((prev) => new Set(prev).add(index));
            onExpansionComplete?.(childThreadId);
        } catch (error) {
            console.error('[SequentialExpansionOptions] Expansion failed:', error);
            onError?.(error as Error);
        } finally {
            setExpandingIndex(null);
        }
    };

    return (
        <div className="space-y-3">
            {/* Header */}
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <Sparkles className="w-4 h-4" />
                <span>{t('chat.expansion.followUpQuestions', 'Follow-up questions')}</span>
                <span className="ml-auto text-xs">
                    {expansion.coherenceScore > 0.7
                        ? t('chat.expansion.highCoherence', 'High coherence')
                        : t('chat.expansion.moderateCoherence', 'Moderate coherence')}
                </span>
            </div>

            {/* Expansion Options */}
            <div className="space-y-2">
                {expansion.questions.map((question, index) => {
                    const isExpanded = expandedThreads.has(index);
                    const isExpanding = expandingIndex === index;
                    // Compute display title outside JSX to avoid syntax issues
                    const displayTitle = question.threadTitle.length > 20
                        ? `${question.threadTitle.slice(0, 20)}...`
                        : question.threadTitle;

                    return (
                        <button
                            key={index}
                            onClick={() => isExpanded ? undefined : handleExpand(index, question)}
                            disabled={isExpanding || expandingIndex !== null}
                            className={`
                                w-full text-left p-3 rounded-lg border transition-all
                                flex items-start gap-3 group
                                ${isExpanded
                                    ? 'bg-success/10 border-success/30 text-success-foreground'
                                    : 'bg-background hover:bg-accent hover:border-accent-border'
                                }
                                ${isExpanding ? 'opacity-70 cursor-wait' : ''}
                                ${expandingIndex !== null && !isExpanding ? 'opacity-50' : ''}
                            `}
                        >
                            {/* Icon */}
                            <div className={`
                                flex-shrink-0 w-6 h-6 rounded-full flex items-center justify-center
                                ${isExpanded
                                    ? 'bg-success text-success-foreground'
                                    : 'bg-primary/10 text-primary group-hover:bg-primary group-hover:text-primary-foreground'
                                }
                            `}>
                                {isExpanding ? (
                                    <Loader2 className="w-3 h-3 animate-spin" />
                                ) : isExpanded ? (
                                    <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                                    </svg>
                                ) : (
                                    <ChevronRight className="w-3 h-3" />
                                )}
                            </div>

                            {/* Content */}
                            <div className="flex-1 min-w-0">
                                <p className={`text-sm font-medium ${isExpanded ? '' : 'group-hover:text-accent-foreground'}`}>
                                    {question.question}
                                </p>
                                {question.rationale && (
                                    <p className="text-xs text-muted-foreground mt-1">
                                        {question.rationale}
                                    </p>
                                )}
                            </div>

                            {/* Thread title indicator */}
                            {!isExpanded && (
                                <span className="text-xs text-muted-foreground flex-shrink-0">
                                    {displayTitle}
                                </span>
                            )}
                        </button>
                    );
                })}
            </div>

            {/* Topic Summary */}
            {expansion.topicSummary && (
                <p className="text-xs text-muted-foreground italic">
                    {t('chat.expansion.topicSummary', 'Topic')}: {expansion.topicSummary}
                </p>
            )}
        </div>
    );
}

// ============================================================================
// Loading State Component
// ============================================================================

export interface SequentialExpansionLoadingProps {
    /** Optional message to display */
    message?: string;
}

/**
 * Loading state for expansion generation
 */
export function SequentialExpansionLoading({
    message,
}: SequentialExpansionLoadingProps) {
    const { t } = useTranslation();

    return (
        <div className="flex items-center gap-3 text-sm text-muted-foreground p-4">
            <Loader2 className="w-5 h-5 animate-spin" />
            <span>
                {message || t('chat.expansion.generating', 'Generating follow-up questions...')}
            </span>
        </div>
    );
}
