/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestFsAdapterRouteImport } from './routes/test-fs-adapter'
import { Route as TestErrorBoundaryRouteImport } from './routes/test-error-boundary'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IdeRouteImport } from './routes/ide'
import { Route as HubRouteImport } from './routes/hub'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as WorkspaceProjectIdRouteImport } from './routes/workspace/$projectId'
import { Route as WebcontainerSplatRouteImport } from './routes/webcontainer.$'
import { Route as NotesProjectIdRouteImport } from './routes/notes.$projectId'
import { Route as IdeProjectIdRouteImport } from './routes/ide.$projectId'
import { Route as ApiProvidersRouteImport } from './routes/api/providers'
import { Route as ApiProviderTestRouteImport } from './routes/api/provider-test'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as __debug_ProviderPlaygroundRouteImport } from './routes/$__debug__.provider-playground'
import { Route as ApiProvidersIdRouteImport } from './routes/api/providers.$id'
import { Route as ApiProvidersIdTestRouteImport } from './routes/api/providers.$id.test'
import { Route as ApiProvidersIdExecuteRouteImport } from './routes/api/providers.$id.execute'

const NotesLazyRouteImport = createFileRoute('/notes')()

const NotesLazyRoute = NotesLazyRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/notes.lazy').then((d) => d.Route))
const TestFsAdapterRoute = TestFsAdapterRouteImport.update({
  id: '/test-fs-adapter',
  path: '/test-fs-adapter',
  getParentRoute: () => rootRouteImport,
} as any)
const TestErrorBoundaryRoute = TestErrorBoundaryRouteImport.update({
  id: '/test-error-boundary',
  path: '/test-error-boundary',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeRoute = IdeRouteImport.update({
  id: '/ide',
  path: '/ide',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceProjectIdRoute = WorkspaceProjectIdRouteImport.update({
  id: '/workspace/$projectId',
  path: '/workspace/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const WebcontainerSplatRoute = WebcontainerSplatRouteImport.update({
  id: '/webcontainer/$',
  path: '/webcontainer/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesProjectIdRoute = NotesProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => NotesLazyRoute,
} as any).lazy(() =>
  import('./routes/notes.$projectId.lazy').then((d) => d.Route),
)
const IdeProjectIdRoute = IdeProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => IdeRoute,
} as any)
const ApiProvidersRoute = ApiProvidersRouteImport.update({
  id: '/api/providers',
  path: '/api/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProviderTestRoute = ApiProviderTestRouteImport.update({
  id: '/api/provider-test',
  path: '/api/provider-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const __debug_ProviderPlaygroundRoute =
  __debug_ProviderPlaygroundRouteImport.update({
    id: '/$__debug__/provider-playground',
    path: '/$__debug_/provider-playground',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProvidersIdRoute = ApiProvidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProvidersRoute,
} as any)
const ApiProvidersIdTestRoute = ApiProvidersIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiProvidersIdRoute,
} as any)
const ApiProvidersIdExecuteRoute = ApiProvidersIdExecuteRouteImport.update({
  id: '/execute',
  path: '/execute',
  getParentRoute: () => ApiProvidersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/debug': typeof DebugRoute
  '/hub': typeof HubRoute
  '/ide': typeof IdeRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/test-error-boundary': typeof TestErrorBoundaryRoute
  '/test-fs-adapter': typeof TestFsAdapterRoute
  '/notes': typeof NotesLazyRouteWithChildren
  '/$__debug_/provider-playground': typeof __debug_ProviderPlaygroundRoute
  '/api/chat': typeof ApiChatRoute
  '/api/provider-test': typeof ApiProviderTestRoute
  '/api/providers': typeof ApiProvidersRouteWithChildren
  '/ide/$projectId': typeof IdeProjectIdRoute
  '/notes/$projectId': typeof NotesProjectIdRoute
  '/webcontainer/$': typeof WebcontainerSplatRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/api/providers/$id': typeof ApiProvidersIdRouteWithChildren
  '/api/providers/$id/execute': typeof ApiProvidersIdExecuteRoute
  '/api/providers/$id/test': typeof ApiProvidersIdTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/debug': typeof DebugRoute
  '/hub': typeof HubRoute
  '/ide': typeof IdeRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/test-error-boundary': typeof TestErrorBoundaryRoute
  '/test-fs-adapter': typeof TestFsAdapterRoute
  '/notes': typeof NotesLazyRouteWithChildren
  '/$__debug_/provider-playground': typeof __debug_ProviderPlaygroundRoute
  '/api/chat': typeof ApiChatRoute
  '/api/provider-test': typeof ApiProviderTestRoute
  '/api/providers': typeof ApiProvidersRouteWithChildren
  '/ide/$projectId': typeof IdeProjectIdRoute
  '/notes/$projectId': typeof NotesProjectIdRoute
  '/webcontainer/$': typeof WebcontainerSplatRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/api/providers/$id': typeof ApiProvidersIdRouteWithChildren
  '/api/providers/$id/execute': typeof ApiProvidersIdExecuteRoute
  '/api/providers/$id/test': typeof ApiProvidersIdTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/debug': typeof DebugRoute
  '/hub': typeof HubRoute
  '/ide': typeof IdeRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/test-error-boundary': typeof TestErrorBoundaryRoute
  '/test-fs-adapter': typeof TestFsAdapterRoute
  '/notes': typeof NotesLazyRouteWithChildren
  '/$__debug__/provider-playground': typeof __debug_ProviderPlaygroundRoute
  '/api/chat': typeof ApiChatRoute
  '/api/provider-test': typeof ApiProviderTestRoute
  '/api/providers': typeof ApiProvidersRouteWithChildren
  '/ide/$projectId': typeof IdeProjectIdRoute
  '/notes/$projectId': typeof NotesProjectIdRoute
  '/webcontainer/$': typeof WebcontainerSplatRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/api/providers/$id': typeof ApiProvidersIdRouteWithChildren
  '/api/providers/$id/execute': typeof ApiProvidersIdExecuteRoute
  '/api/providers/$id/test': typeof ApiProvidersIdTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/debug'
    | '/hub'
    | '/ide'
    | '/projects'
    | '/settings'
    | '/test-error-boundary'
    | '/test-fs-adapter'
    | '/notes'
    | '/$__debug_/provider-playground'
    | '/api/chat'
    | '/api/provider-test'
    | '/api/providers'
    | '/ide/$projectId'
    | '/notes/$projectId'
    | '/webcontainer/$'
    | '/workspace/$projectId'
    | '/workspace'
    | '/api/providers/$id'
    | '/api/providers/$id/execute'
    | '/api/providers/$id/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/debug'
    | '/hub'
    | '/ide'
    | '/projects'
    | '/settings'
    | '/test-error-boundary'
    | '/test-fs-adapter'
    | '/notes'
    | '/$__debug_/provider-playground'
    | '/api/chat'
    | '/api/provider-test'
    | '/api/providers'
    | '/ide/$projectId'
    | '/notes/$projectId'
    | '/webcontainer/$'
    | '/workspace/$projectId'
    | '/workspace'
    | '/api/providers/$id'
    | '/api/providers/$id/execute'
    | '/api/providers/$id/test'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agents'
    | '/debug'
    | '/hub'
    | '/ide'
    | '/projects'
    | '/settings'
    | '/test-error-boundary'
    | '/test-fs-adapter'
    | '/notes'
    | '/$__debug__/provider-playground'
    | '/api/chat'
    | '/api/provider-test'
    | '/api/providers'
    | '/ide/$projectId'
    | '/notes/$projectId'
    | '/webcontainer/$'
    | '/workspace/$projectId'
    | '/workspace/'
    | '/api/providers/$id'
    | '/api/providers/$id/execute'
    | '/api/providers/$id/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  DebugRoute: typeof DebugRoute
  HubRoute: typeof HubRoute
  IdeRoute: typeof IdeRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  TestErrorBoundaryRoute: typeof TestErrorBoundaryRoute
  TestFsAdapterRoute: typeof TestFsAdapterRoute
  NotesLazyRoute: typeof NotesLazyRouteWithChildren
  __debug_ProviderPlaygroundRoute: typeof __debug_ProviderPlaygroundRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiProviderTestRoute: typeof ApiProviderTestRoute
  ApiProvidersRoute: typeof ApiProvidersRouteWithChildren
  WebcontainerSplatRoute: typeof WebcontainerSplatRoute
  WorkspaceProjectIdRoute: typeof WorkspaceProjectIdRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-fs-adapter': {
      id: '/test-fs-adapter'
      path: '/test-fs-adapter'
      fullPath: '/test-fs-adapter'
      preLoaderRoute: typeof TestFsAdapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-error-boundary': {
      id: '/test-error-boundary'
      path: '/test-error-boundary'
      fullPath: '/test-error-boundary'
      preLoaderRoute: typeof TestErrorBoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ide': {
      id: '/ide'
      path: '/ide'
      fullPath: '/ide'
      preLoaderRoute: typeof IdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$projectId': {
      id: '/workspace/$projectId'
      path: '/workspace/$projectId'
      fullPath: '/workspace/$projectId'
      preLoaderRoute: typeof WorkspaceProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webcontainer/$': {
      id: '/webcontainer/$'
      path: '/webcontainer/$'
      fullPath: '/webcontainer/$'
      preLoaderRoute: typeof WebcontainerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$projectId': {
      id: '/notes/$projectId'
      path: '/$projectId'
      fullPath: '/notes/$projectId'
      preLoaderRoute: typeof NotesProjectIdRouteImport
      parentRoute: typeof NotesLazyRoute
    }
    '/ide/$projectId': {
      id: '/ide/$projectId'
      path: '/$projectId'
      fullPath: '/ide/$projectId'
      preLoaderRoute: typeof IdeProjectIdRouteImport
      parentRoute: typeof IdeRoute
    }
    '/api/providers': {
      id: '/api/providers'
      path: '/api/providers'
      fullPath: '/api/providers'
      preLoaderRoute: typeof ApiProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider-test': {
      id: '/api/provider-test'
      path: '/api/provider-test'
      fullPath: '/api/provider-test'
      preLoaderRoute: typeof ApiProviderTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$__debug__/provider-playground': {
      id: '/$__debug__/provider-playground'
      path: '/$__debug_/provider-playground'
      fullPath: '/$__debug_/provider-playground'
      preLoaderRoute: typeof __debug_ProviderPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers/$id': {
      id: '/api/providers/$id'
      path: '/$id'
      fullPath: '/api/providers/$id'
      preLoaderRoute: typeof ApiProvidersIdRouteImport
      parentRoute: typeof ApiProvidersRoute
    }
    '/api/providers/$id/test': {
      id: '/api/providers/$id/test'
      path: '/test'
      fullPath: '/api/providers/$id/test'
      preLoaderRoute: typeof ApiProvidersIdTestRouteImport
      parentRoute: typeof ApiProvidersIdRoute
    }
    '/api/providers/$id/execute': {
      id: '/api/providers/$id/execute'
      path: '/execute'
      fullPath: '/api/providers/$id/execute'
      preLoaderRoute: typeof ApiProvidersIdExecuteRouteImport
      parentRoute: typeof ApiProvidersIdRoute
    }
  }
}

interface IdeRouteChildren {
  IdeProjectIdRoute: typeof IdeProjectIdRoute
}

const IdeRouteChildren: IdeRouteChildren = {
  IdeProjectIdRoute: IdeProjectIdRoute,
}

const IdeRouteWithChildren = IdeRoute._addFileChildren(IdeRouteChildren)

interface NotesLazyRouteChildren {
  NotesProjectIdRoute: typeof NotesProjectIdRoute
}

const NotesLazyRouteChildren: NotesLazyRouteChildren = {
  NotesProjectIdRoute: NotesProjectIdRoute,
}

const NotesLazyRouteWithChildren = NotesLazyRoute._addFileChildren(
  NotesLazyRouteChildren,
)

interface ApiProvidersIdRouteChildren {
  ApiProvidersIdExecuteRoute: typeof ApiProvidersIdExecuteRoute
  ApiProvidersIdTestRoute: typeof ApiProvidersIdTestRoute
}

const ApiProvidersIdRouteChildren: ApiProvidersIdRouteChildren = {
  ApiProvidersIdExecuteRoute: ApiProvidersIdExecuteRoute,
  ApiProvidersIdTestRoute: ApiProvidersIdTestRoute,
}

const ApiProvidersIdRouteWithChildren = ApiProvidersIdRoute._addFileChildren(
  ApiProvidersIdRouteChildren,
)

interface ApiProvidersRouteChildren {
  ApiProvidersIdRoute: typeof ApiProvidersIdRouteWithChildren
}

const ApiProvidersRouteChildren: ApiProvidersRouteChildren = {
  ApiProvidersIdRoute: ApiProvidersIdRouteWithChildren,
}

const ApiProvidersRouteWithChildren = ApiProvidersRoute._addFileChildren(
  ApiProvidersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  DebugRoute: DebugRoute,
  HubRoute: HubRoute,
  IdeRoute: IdeRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  TestErrorBoundaryRoute: TestErrorBoundaryRoute,
  TestFsAdapterRoute: TestFsAdapterRoute,
  NotesLazyRoute: NotesLazyRouteWithChildren,
  __debug_ProviderPlaygroundRoute: __debug_ProviderPlaygroundRoute,
  ApiChatRoute: ApiChatRoute,
  ApiProviderTestRoute: ApiProviderTestRoute,
  ApiProvidersRoute: ApiProvidersRouteWithChildren,
  WebcontainerSplatRoute: WebcontainerSplatRoute,
  WorkspaceProjectIdRoute: WorkspaceProjectIdRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
