/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestFsAdapterRouteImport } from './routes/test-fs-adapter'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as IdeRouteImport } from './routes/ide'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as WorkspaceProjectIdRouteImport } from './routes/workspace/$projectId'
import { Route as WebcontainerSplatRouteImport } from './routes/webcontainer.$'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiQuizzesGenerateRouteImport } from './routes/api/quizzes/generate'
import { Route as ApiFlashcardsGenerateRouteImport } from './routes/api/flashcards/generate'

const TestFsAdapterRoute = TestFsAdapterRouteImport.update({
  id: '/test-fs-adapter',
  path: '/test-fs-adapter',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeRoute = IdeRouteImport.update({
  id: '/ide',
  path: '/ide',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceProjectIdRoute = WorkspaceProjectIdRouteImport.update({
  id: '/workspace/$projectId',
  path: '/workspace/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const WebcontainerSplatRoute = WebcontainerSplatRouteImport.update({
  id: '/webcontainer/$',
  path: '/webcontainer/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuizzesGenerateRoute = ApiQuizzesGenerateRouteImport.update({
  id: '/api/quizzes/generate',
  path: '/api/quizzes/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlashcardsGenerateRoute = ApiFlashcardsGenerateRouteImport.update({
  id: '/api/flashcards/generate',
  path: '/api/flashcards/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/ide': typeof IdeRoute
  '/knowledge': typeof KnowledgeRoute
  '/settings': typeof SettingsRoute
  '/study': typeof StudyRoute
  '/test-fs-adapter': typeof TestFsAdapterRoute
  '/api/chat': typeof ApiChatRoute
  '/webcontainer/$': typeof WebcontainerSplatRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/api/flashcards/generate': typeof ApiFlashcardsGenerateRoute
  '/api/quizzes/generate': typeof ApiQuizzesGenerateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/ide': typeof IdeRoute
  '/knowledge': typeof KnowledgeRoute
  '/settings': typeof SettingsRoute
  '/study': typeof StudyRoute
  '/test-fs-adapter': typeof TestFsAdapterRoute
  '/api/chat': typeof ApiChatRoute
  '/webcontainer/$': typeof WebcontainerSplatRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/api/flashcards/generate': typeof ApiFlashcardsGenerateRoute
  '/api/quizzes/generate': typeof ApiQuizzesGenerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/ide': typeof IdeRoute
  '/knowledge': typeof KnowledgeRoute
  '/settings': typeof SettingsRoute
  '/study': typeof StudyRoute
  '/test-fs-adapter': typeof TestFsAdapterRoute
  '/api/chat': typeof ApiChatRoute
  '/webcontainer/$': typeof WebcontainerSplatRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/api/flashcards/generate': typeof ApiFlashcardsGenerateRoute
  '/api/quizzes/generate': typeof ApiQuizzesGenerateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/ide'
    | '/knowledge'
    | '/settings'
    | '/study'
    | '/test-fs-adapter'
    | '/api/chat'
    | '/webcontainer/$'
    | '/workspace/$projectId'
    | '/workspace'
    | '/api/flashcards/generate'
    | '/api/quizzes/generate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/ide'
    | '/knowledge'
    | '/settings'
    | '/study'
    | '/test-fs-adapter'
    | '/api/chat'
    | '/webcontainer/$'
    | '/workspace/$projectId'
    | '/workspace'
    | '/api/flashcards/generate'
    | '/api/quizzes/generate'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agents'
    | '/ide'
    | '/knowledge'
    | '/settings'
    | '/study'
    | '/test-fs-adapter'
    | '/api/chat'
    | '/webcontainer/$'
    | '/workspace/$projectId'
    | '/workspace/'
    | '/api/flashcards/generate'
    | '/api/quizzes/generate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  IdeRoute: typeof IdeRoute
  KnowledgeRoute: typeof KnowledgeRoute
  SettingsRoute: typeof SettingsRoute
  StudyRoute: typeof StudyRoute
  TestFsAdapterRoute: typeof TestFsAdapterRoute
  ApiChatRoute: typeof ApiChatRoute
  WebcontainerSplatRoute: typeof WebcontainerSplatRoute
  WorkspaceProjectIdRoute: typeof WorkspaceProjectIdRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  ApiFlashcardsGenerateRoute: typeof ApiFlashcardsGenerateRoute
  ApiQuizzesGenerateRoute: typeof ApiQuizzesGenerateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-fs-adapter': {
      id: '/test-fs-adapter'
      path: '/test-fs-adapter'
      fullPath: '/test-fs-adapter'
      preLoaderRoute: typeof TestFsAdapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ide': {
      id: '/ide'
      path: '/ide'
      fullPath: '/ide'
      preLoaderRoute: typeof IdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$projectId': {
      id: '/workspace/$projectId'
      path: '/workspace/$projectId'
      fullPath: '/workspace/$projectId'
      preLoaderRoute: typeof WorkspaceProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webcontainer/$': {
      id: '/webcontainer/$'
      path: '/webcontainer/$'
      fullPath: '/webcontainer/$'
      preLoaderRoute: typeof WebcontainerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quizzes/generate': {
      id: '/api/quizzes/generate'
      path: '/api/quizzes/generate'
      fullPath: '/api/quizzes/generate'
      preLoaderRoute: typeof ApiQuizzesGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flashcards/generate': {
      id: '/api/flashcards/generate'
      path: '/api/flashcards/generate'
      fullPath: '/api/flashcards/generate'
      preLoaderRoute: typeof ApiFlashcardsGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  IdeRoute: IdeRoute,
  KnowledgeRoute: KnowledgeRoute,
  SettingsRoute: SettingsRoute,
  StudyRoute: StudyRoute,
  TestFsAdapterRoute: TestFsAdapterRoute,
  ApiChatRoute: ApiChatRoute,
  WebcontainerSplatRoute: WebcontainerSplatRoute,
  WorkspaceProjectIdRoute: WorkspaceProjectIdRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  ApiFlashcardsGenerateRoute: ApiFlashcardsGenerateRoute,
  ApiQuizzesGenerateRoute: ApiQuizzesGenerateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
