/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestFsAdapterRouteImport } from './routes/test-fs-adapter'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as IdeRouteImport } from './routes/ide'
import { Route as HubRouteImport } from './routes/hub'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceProjectIdRouteImport } from './routes/workspace/$projectId'
import { Route as WebcontainerSplatRouteImport } from './routes/webcontainer.$'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TestFsAdapterRoute = TestFsAdapterRouteImport.update({
  id: '/test-fs-adapter',
  path: '/test-fs-adapter',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeRoute = IdeRouteImport.update({
  id: '/ide',
  path: '/ide',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceProjectIdRoute = WorkspaceProjectIdRouteImport.update({
  id: '/workspace/$projectId',
  path: '/workspace/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const WebcontainerSplatRoute = WebcontainerSplatRouteImport.update({
  id: '/webcontainer/$',
  path: '/webcontainer/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/hub': typeof HubRoute
  '/ide': typeof IdeRoute
  '/knowledge': typeof KnowledgeRoute
  '/settings': typeof SettingsRoute
  '/test-fs-adapter': typeof TestFsAdapterRoute
  '/api/chat': typeof ApiChatRoute
  '/webcontainer/$': typeof WebcontainerSplatRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/hub': typeof HubRoute
  '/ide': typeof IdeRoute
  '/knowledge': typeof KnowledgeRoute
  '/settings': typeof SettingsRoute
  '/test-fs-adapter': typeof TestFsAdapterRoute
  '/api/chat': typeof ApiChatRoute
  '/webcontainer/$': typeof WebcontainerSplatRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/hub': typeof HubRoute
  '/ide': typeof IdeRoute
  '/knowledge': typeof KnowledgeRoute
  '/settings': typeof SettingsRoute
  '/test-fs-adapter': typeof TestFsAdapterRoute
  '/api/chat': typeof ApiChatRoute
  '/webcontainer/$': typeof WebcontainerSplatRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/hub'
    | '/ide'
    | '/knowledge'
    | '/settings'
    | '/test-fs-adapter'
    | '/api/chat'
    | '/webcontainer/$'
    | '/workspace/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/hub'
    | '/ide'
    | '/knowledge'
    | '/settings'
    | '/test-fs-adapter'
    | '/api/chat'
    | '/webcontainer/$'
    | '/workspace/$projectId'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/hub'
    | '/ide'
    | '/knowledge'
    | '/settings'
    | '/test-fs-adapter'
    | '/api/chat'
    | '/webcontainer/$'
    | '/workspace/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  HubRoute: typeof HubRoute
  IdeRoute: typeof IdeRoute
  KnowledgeRoute: typeof KnowledgeRoute
  SettingsRoute: typeof SettingsRoute
  TestFsAdapterRoute: typeof TestFsAdapterRoute
  ApiChatRoute: typeof ApiChatRoute
  WebcontainerSplatRoute: typeof WebcontainerSplatRoute
  WorkspaceProjectIdRoute: typeof WorkspaceProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-fs-adapter': {
      id: '/test-fs-adapter'
      path: '/test-fs-adapter'
      fullPath: '/test-fs-adapter'
      preLoaderRoute: typeof TestFsAdapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ide': {
      id: '/ide'
      path: '/ide'
      fullPath: '/ide'
      preLoaderRoute: typeof IdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$projectId': {
      id: '/workspace/$projectId'
      path: '/workspace/$projectId'
      fullPath: '/workspace/$projectId'
      preLoaderRoute: typeof WorkspaceProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webcontainer/$': {
      id: '/webcontainer/$'
      path: '/webcontainer/$'
      fullPath: '/webcontainer/$'
      preLoaderRoute: typeof WebcontainerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  HubRoute: HubRoute,
  IdeRoute: IdeRoute,
  KnowledgeRoute: KnowledgeRoute,
  SettingsRoute: SettingsRoute,
  TestFsAdapterRoute: TestFsAdapterRoute,
  ApiChatRoute: ApiChatRoute,
  WebcontainerSplatRoute: WebcontainerSplatRoute,
  WorkspaceProjectIdRoute: WorkspaceProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
