/**
 * BMAD Beast Mode v2.0.0 - State Sync Plugin
 * 
 * Automatically updates AGENT-STATE.yaml after every meaningful action.
 * Ensures state persistence across sessions and context compaction.
 * 
 * @location .opencode/plugins/post-execution/state-sync-plugin.ts
 * @version 1.0.0
 * @date 2026-01-29
 */

import * as fs from 'fs'
import * as path from 'path'

// ============================================================================
// TYPE DEFINITIONS
// ============================================================================

interface ToolInput {
    tool: string
    args: Record<string, any>
}

interface ToolResult {
    success: boolean
    output?: any
    error?: string
}

interface HookHandler {
    (input: ToolInput, result: ToolResult): Promise<void>
}

interface Plugin {
    name: string
    version: string
    hooks: {
        "tool.execute.after"?: HookHandler
    }
}

interface AgentState {
    session_id: string
    last_updated: string
    current_agent: string | null
    current_story: string | null
    current_phase: "PLANNING" | "EXECUTION" | "VERIFICATION" | null
    last_action: {
        tool: string
        timestamp: string
        status: "success" | "failure"
        target?: string
    } | null
    context_loaded: string[]
    artifacts_modified: string[]
    delegation_stack: Array<{
        from: string
        to: string
        timestamp: string
        story_id?: string
    }>
    governance_events: Array<{
        type: string
        timestamp: string
        message: string
    }>
}

// ============================================================================
// CONFIGURATION
// ============================================================================

const STATE_FILE = ".opencode/state/AGENT-STATE.yaml"
const MAX_ARTIFACTS_TRACKED = 20
const MAX_GOVERNANCE_EVENTS = 10

/**
 * Tools that are passive (don't modify state)
 */
const PASSIVE_TOOLS = [
    "read",
    "read_file",
    "view_file",
    "glob",
    "grep",
    "ls",
    "list_dir",
    "search"
]

/**
 * Tools that modify artifacts
 */
const MODIFY_TOOLS = [
    "write",
    "write_file",
    "edit",
    "edit_file",
    "create_file",
    "patch"
]

// ============================================================================
// STATE MANAGEMENT
// ============================================================================

/**
 * Load current state from file
 */
async function loadState(): Promise<AgentState> {
    const defaultState: AgentState = {
        session_id: `session_${Date.now()}`,
        last_updated: new Date().toISOString(),
        current_agent: null,
        current_story: null,
        current_phase: null,
        last_action: null,
        context_loaded: [],
        artifacts_modified: [],
        delegation_stack: [],
        governance_events: []
    }

    try {
        if (fs.existsSync(STATE_FILE)) {
            const content = fs.readFileSync(STATE_FILE, 'utf-8')
            // Parse YAML (simplified)
            const parsed = parseSimpleYaml(content)
            return { ...defaultState, ...parsed }
        }
    } catch (error) {
        console.error("Error loading agent state:", error)
    }

    return defaultState
}

/**
 * Save state to file
 */
async function saveState(state: AgentState): Promise<void> {
    try {
        // Ensure directory exists
        const dir = path.dirname(STATE_FILE)
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true })
        }

        const yaml = serializeStateToYaml(state)
        fs.writeFileSync(STATE_FILE, yaml)
    } catch (error) {
        console.error("Error saving agent state:", error)
    }
}

/**
 * Simple YAML parser
 */
function parseSimpleYaml(content: string): Partial<AgentState> {
    const result: any = {}
    const lines = content.split('\n')

    for (const line of lines) {
        if (line.startsWith('#') || !line.trim()) continue

        const colonIdx = line.indexOf(':')
        if (colonIdx > 0 && !line.startsWith(' ')) {
            const key = line.substring(0, colonIdx).trim()
            let value = line.substring(colonIdx + 1).trim()

            // Remove quotes
            if (value.startsWith('"') && value.endsWith('"')) {
                value = value.slice(1, -1)
            }

            if (value === 'null') {
                result[key] = null
            } else if (!isNaN(Number(value))) {
                result[key] = Number(value)
            } else {
                result[key] = value
            }
        }
    }

    return result
}

/**
 * Serialize state to YAML
 */
function serializeStateToYaml(state: AgentState): string {
    let yaml = `# BMAD Beast Mode - Agent State\n`
    yaml += `# Auto-generated by state-sync-plugin\n`
    yaml += `# Last Updated: ${state.last_updated}\n\n`

    yaml += `session_id: "${state.session_id}"\n`
    yaml += `last_updated: "${state.last_updated}"\n`
    yaml += `current_agent: ${state.current_agent ? `"${state.current_agent}"` : 'null'}\n`
    yaml += `current_story: ${state.current_story ? `"${state.current_story}"` : 'null'}\n`
    yaml += `current_phase: ${state.current_phase ? `"${state.current_phase}"` : 'null'}\n\n`

    if (state.last_action) {
        yaml += `last_action:\n`
        yaml += `  tool: "${state.last_action.tool}"\n`
        yaml += `  timestamp: "${state.last_action.timestamp}"\n`
        yaml += `  status: "${state.last_action.status}"\n`
        if (state.last_action.target) {
            yaml += `  target: "${state.last_action.target}"\n`
        }
    } else {
        yaml += `last_action: null\n`
    }

    yaml += `\ncontext_loaded:\n`
    for (const ctx of state.context_loaded.slice(-10)) {
        yaml += `  - "${ctx}"\n`
    }

    yaml += `\nartifacts_modified:\n`
    for (const art of state.artifacts_modified.slice(-MAX_ARTIFACTS_TRACKED)) {
        yaml += `  - "${art}"\n`
    }

    yaml += `\ngovernance_events:\n`
    for (const event of state.governance_events.slice(-MAX_GOVERNANCE_EVENTS)) {
        yaml += `  - type: "${event.type}"\n`
        yaml += `    timestamp: "${event.timestamp}"\n`
        yaml += `    message: "${event.message.replace(/"/g, '\\"')}"\n`
    }

    return yaml
}

// ============================================================================
// PLUGIN IMPLEMENTATION
// ============================================================================

export const StateSyncPlugin: Plugin = {
    name: "state-sync-plugin",
    version: "1.0.0",

    hooks: {
        /**
         * After tool execution hook
         * Updates AGENT-STATE.yaml after meaningful actions
         */
        "tool.execute.after": async (input: ToolInput, result: ToolResult): Promise<void> => {
            // Skip passive tools
            if (PASSIVE_TOOLS.some(pt => input.tool.toLowerCase().includes(pt))) {
                // But track context loading for read
                if (input.tool.toLowerCase().includes("read")) {
                    const state = await loadState()
                    const filePath = input.args.path || input.args.filePath
                    if (filePath && !state.context_loaded.includes(filePath)) {
                        state.context_loaded.push(filePath)
                        // Keep only last 10
                        if (state.context_loaded.length > 10) {
                            state.context_loaded = state.context_loaded.slice(-10)
                        }
                        state.last_updated = new Date().toISOString()
                        await saveState(state)
                    }
                }
                return
            }

            // Load current state
            const state = await loadState()

            // Update last action
            state.last_action = {
                tool: input.tool,
                timestamp: new Date().toISOString(),
                status: result.success ? "success" : "failure",
                target: input.args.path || input.args.filePath || input.args.file
            }

            // Track modified artifacts
            if (MODIFY_TOOLS.some(mt => input.tool.toLowerCase().includes(mt))) {
                const filePath = input.args.path || input.args.filePath || input.args.file
                if (filePath && !state.artifacts_modified.includes(filePath)) {
                    state.artifacts_modified.push(filePath)
                    // Keep only last N
                    if (state.artifacts_modified.length > MAX_ARTIFACTS_TRACKED) {
                        state.artifacts_modified = state.artifacts_modified.slice(-MAX_ARTIFACTS_TRACKED)
                    }
                }
            }

            // Update timestamp
            state.last_updated = new Date().toISOString()

            // Save state
            await saveState(state)
        }
    }
}

// ============================================================================
// UTILITY EXPORTS
// ============================================================================

/**
 * Get current agent state (for debugging)
 */
export async function getAgentState(): Promise<AgentState> {
    return loadState()
}

/**
 * Add governance event
 */
export async function addGovernanceEvent(type: string, message: string): Promise<void> {
    const state = await loadState()
    state.governance_events.push({
        type,
        timestamp: new Date().toISOString(),
        message
    })
    if (state.governance_events.length > MAX_GOVERNANCE_EVENTS) {
        state.governance_events = state.governance_events.slice(-MAX_GOVERNANCE_EVENTS)
    }
    await saveState(state)
}

/**
 * Set current story
 */
export async function setCurrentStory(storyId: string | null): Promise<void> {
    const state = await loadState()
    state.current_story = storyId
    state.last_updated = new Date().toISOString()
    await saveState(state)
}

/**
 * Set current phase
 */
export async function setCurrentPhase(phase: AgentState['current_phase']): Promise<void> {
    const state = await loadState()
    state.current_phase = phase
    state.last_updated = new Date().toISOString()
    await saveState(state)
}

// Export as default for plugin loading
export default StateSyncPlugin
